name: Run a test
# This workflow is triggered on pushes to the repository.
on: 
  check_run:
    types: [completed]
  
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'this ran when the other one ran'
