name: conditional run
# This workflow is triggered on pushes to the repository.
on: 
  check_run:
    types: [completed]

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: conditionalRun
        uses: sofisl/checkRunAction@v9
        with:
          conclusion: ${{ github.event.check_run.conclusion }}
          pull_request_head_sha: ${{ github.event.pull_requests[0].head.sha }}
          author: ${{ github.actor }}
          myToken: ${{ github.token }}
   
