name: summary check
# This workflow is triggered on check runs
on: 
  status

jobs:
  summary_check_samples:
    runs-on: ubuntu-latest
    steps:
      - name: summary_check_samples
        uses: sofisl/check-run-action@v12.0.4
        with:
          conclusion: ${{ github.event.state }}
          pull_request_head_sha: ${{ github.event.sha }}
          myToken: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          testName: ${{ github.event.context }}
          testNameToCheckAgainst: 'hello'
          testAuthorToCheckAgainst: 'sofisl'
   
